name: 'BUSL Blocker'
description: 'BUSL Blocker'
inputs:
  module-path:
    description: 'Path to the go module you want to test'
    required: true
  ignore-modules:
    description: 'Comma separated list of modules to ignore'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: GOBIN="${{ github.action_path }}/bin/" go install github.com/pulumi/go-licenses@ec48b64
      shell: bash
    - run: echo "${{ github.action_path }}/bin/" >> $GITHUB_PATH
      shell: bash
    # We ignore the module being checked (go list -m) because we often cannot detect our own LICENSE.
    # golang will copy the LICENSE from the repo root into each package without its own when pulling
    # dependencies, but that doesn't occur when we're running against a raw checkout.
    - run: |
        go-licenses check ./... --ignore $(go list -m) --include_tests \
        --ignore $(tr -d ' \n' <<<"${{ inputs.ignore-modules }}") \
        --ignore $(go list std | awk 'NR > 1 { printf(",") } { printf("%s",$0) } END { print "" }')
      working-directory: ${{ inputs.module-path }}
      shell: bash
